### PR TITLE
Add database and more

### PR DESCRIPTION
**Pull request by AnimeDevOps**
I added database functionality, check for new episodes on all series downloaded, and you can show all downloaded anime url and anime, and fixed a small problem with the script always check if you already have the episode downloaded, thanks for taking your time and reading.

### CODE REVIEW

**Comment by EpicUnknown** [comment]
Love the changes! I feels like what I was doing for "MyAnimeDownloader" where I had a cache.json which stored ALL this data you are currently doing haha

Small change requests, let me know what you think.

In Settings.py you have
```python        
if (os.name == 'posix'):
    self.loaded_settings['downloadsDatabaseLocation'] = "./database.p"
elif (os.name == 'nt'):
    self.loaded_settings['downloadsDatabaseLocation'] = ".\\database.p"
```

Why not make it simply
```python
self.loaded_settings['downloadsDatabaseLocation'] = "." + os.sep + "database.p"
```

`os.sep` will choose the correct path depending on the OS. You could also use `os.path.sep` and it will do the same thing but will be easier to read to everyone else.

Let me know what you think and I'll merge afterwards (:

**Comment by EpicUnknown** [comment]
This is how my `cache.json` looks for MyAnimeDownloader
```json
"Show Name Here": {
        "download_location": "",
        "episodes": "53",
        "seasons": "3",
        "type": "cartoon",
        "url": "https://www.wcostream.com/anime/show-name-here"
    }
```

Type could be Subbed, Dubbed or Cartoon and when you download that show it will save the place you downloaded it in the `download_location`. I'm glad to see you have brought something similar over! Thank you!

**Comment by AnimeDevOps** [comment]
> Love the changes! I feels like what I was doing for "MyAnimeDownloader" where I had a cache.json which stored ALL this data you are currently doing haha
> 
> Small change requests, let me know what you think.
> 
> In Settings.py you have
> 
> ```python
> if (os.name == 'posix'):
>     self.loaded_settings['downloadsDatabaseLocation'] = "./database.p"
> elif (os.name == 'nt'):
>     self.loaded_settings['downloadsDatabaseLocation'] = ".\\database.p"
> ```
> 
> Why not make it simply
> 
> ```python
> self.loaded_settings['downloadsDatabaseLocation'] = "." + os.sep + "database.p"
> ```
> 
> `os.sep` will choose the correct path depending on the OS. You could also use `os.path.sep` and it will do the same thing but will be more clear on what it is doing to everyone else.
> 
> Let me know what you think and I'll merge afterwards (:

that's nice, it's a better way of looking for correct OS path, thanks I didn't know that, I'll be adding a resume download feature to the script, in a few hours ok.

**Comment by AnimeDevOps** [comment]
> This is how my `cache.json` looks for MyAnimeDownloader
> 
> ```json
> "Show Name Here": {
>         "download_location": "",
>         "episodes": "53",
>         "seasons": "3",
>         "type": "cartoon",
>         "url": "https://www.wcostream.com/anime/show-name-here"
>     }
> ```
> 
> Type could be Subbed, Dubbed or Cartoon and when you download that show it will save the place you downloaded it in the `download_location`. I'm glad to see you have brought something similar over! Thank you!

this is a better way of doing things, I'll check out the code later.

**Comment by EpicUnknown** [comment]
Just let me know when you want me to test it out and merge it! (:

**Comment by AnimeDevOps** [comment]
> Just let me know when you want me to test it out and merge it! (:

I finished adding the resuming feature on the script, and I tested it seems to work fine, but I can't make a pull requests.
you can find the changes on my fork, and try it out, have fun!

**Comment by EpicUnknown** [comment]
I noticed in `Downloader.py` you print out that the user can turn off resume downloads but it doesn't check that setting anywhere that I see? Did I miss that?

Also you don't have to make a new pull request. Any changes you make to your master branch will auto populate here in this pull request.

**Comment by AnimeDevOps** [comment]
> I noticed in `Downloader.py` you print out that the user can turn off resume downloads but it doesn't check that setting anywhere that I see? Did I miss that?
> 
> Also you don't have to make a new pull request. Any changes you make to your master branch will auto populate here in this pull request.

Yeah, I forgot to put it in, I just fixed it, everything should be fine now. :)

**Pull request merged**
